### ISSUE TITLE
Manage Animations Hides

### ISSUE THREAD

**Issue by teknoziz** [tumult/hype-wordpress-plugin#1]
The Manage Animations section hides even if there is enough space for it to appear, until you scroll down.

**Comment by themorgantown** [comment]
Can you post a screenshot and provide more information about how to reproduce? Browser & Version?

**Comment by teknoziz** [comment]
![capto_capture 2017-09-13_05-28-03_pm](https://user-images.githubusercontent.com/7119442/30401689-2348800c-98a9-11e7-924d-716a5640a982.png)

Chrome for Mac version 60 this was when there were animations.

**Comment by themorgantown** [comment]
This appears to be fixed (nothing I did).  

Can you check @teknoziz ?
