### ISSUE TITLE
Console warning: Non unique Ids

### ISSUE THREAD

**Issue by david-gap** [tumult/hype-wordpress-plugin#17]
Console warning: two input fields with the same ID.
And not only in admin.php?page=hypeanimations_panel (in every page)

![Tumult-Hype-Animations](https://user-images.githubusercontent.com/23354033/90150295-cdb80700-dd85-11ea-991d-6ceabd1dd9da.jpg)

**Comment by themorgantown** [comment]
This is resolved in the latest beta if you'd like to test: https://github.com/tumult/hype-wordpress-plugin/releases
