### ISSUE TITLE
Responsive Animation Still Doesn't Appear

### ISSUE THREAD

**Issue by teknoziz** [tumult/hype-wordpress-plugin#2]
Placing a responsive animation doesn't display when viewing.

http://trdesign.wpengine.com/maxit/ 

Look under the toggle reading "THE MOST HIGHLY AUTOMATED COST BASIS PLATFORM." Animation should appear above purple text at bottom.

**Comment by themorgantown** [comment]
I see the Hype document: https://cl.ly/1x1Q3s2G3X1S 

Do you see any errors in your browser console?

**Comment by teknoziz** [comment]
That’s odd, I even cleared the cache. Only when I manually resized the window did it appear. However when sizing the window down to the breakpoint the animation does disappear.

Sincerely,

David Zizza, TeKno Ziz
(617) 543-3971 cell    (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com>
teknoziz.com <http://teknoziz.com/>

**Comment by teknoziz** [comment]
So looking at this again. On initial page access, the animation is hidden from review until the window is resized.

![capto_capture 2017-09-14_11-38-56_am](https://user-images.githubusercontent.com/7119442/30439348-7d37823c-9941-11e7-99d2-cc16a39c8fe7.png)
