### ISSUE TITLE
Importing OAM to Wordpress 6.03

### ISSUE THREAD

**Issue by Gcanal49** [tumult/hype-wordpress-plugin#24]
Bug Report:  When upload oam archive the plugin duiplicate it. and the shortcode doesn´t works. 
![Captura de Pantalla 2022-10-20 a la(s) 12 38 20 p m](https://user-images.githubusercontent.com/103293167/197019968-a2897c69-7f06-4755-b3f3-76b2c5b69c19.png)

**Comment by Gcanal49** [comment]
![Captura de Pantalla 2022-10-20 a la(s) 12 42 16 p m](https://user-images.githubusercontent.com/103293167/197020601-3035895b-7c54-4502-bf11-4e82936ab7a6.png)

**Comment by themorgantown** [comment]
Sorry you're hitting this issue. Can you give me a bit more info? PHP version, Wordpress version, and a zip file of your .hype file? 
Can you also confirm that your Hype document does not have a 100% value for the height? There's more info on how to [avoid scaling + responsive issues here](https://forums.tumult.com/t/tumult-hype-animations-wordpress-plugin/11074#responsive-document-tips-2).

**Comment by Gcanal49** [comment]
thanks for answer me, the php version is "PHP Version 7.4.30" 
[slider.oam.zip](https://github.com/tumult/hype-wordpress-plugin/files/9834464/slider.oam.zip), I dont remember the height because  I delete the original hype file..

**Comment by Gcanal49** [comment]
hi themorgantown, i update de height in a new hype document and works great!. thanks so much
