### ISSUE TITLE
Adding iFrame Crashes Server

### ISSUE THREAD

**Issue by teknoziz** [tumult/hype-wordpress-plugin#3]
Using an iFrame instead of DIV to wrap the animation yields the following:

**Internal Server Error**

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by themorgantown** [comment]
Can you please provide the PHP version and Wordpress version of your server?

**Comment by teknoziz** [comment]
WordPress 4.8.1 WPMU found this in the log:

[Wed Sep 13 21:26:47.879336 2017] [core:error] [pid 21821] [client 173.76.8.119:60154] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: https://trdesign.wpengine.com/maxit/wp-content/plugins/hype-wordpress-plugin-master/css/jquery.dataTables.min.css?ver=1.0.0

**Comment by teknoziz** [comment]
PHP 5.6

**Comment by themorgantown** [comment]
Can you try with the latest update?

**Comment by teknoziz** [comment]
Crashes with same error.

**Comment by themorgantown** [comment]
Any way you could send me a PM on the forums? https://forums.tumult.com/u/Daniel/activity Hoping to log in and diagnose.

**Comment by teknoziz** [comment]
I’m on the forum, can’t figure how to PM…

Sincerely,

David Zizza, TeKno Ziz
(617) 543-3971 cell    (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com>
teknoziz.com <http://teknoziz.com/>

**Comment by themorgantown** [comment]
Can you test this with the latest @teknoziz?

**Comment by teknoziz** [comment]
iFrame no longer crashes. But it seems as though the iFrame does not encompass the size of the animation, it’s about a third of the height. And the div does not appear at all at first. If you resize the window a little, it appears. When shrinking the window size down, it will disappear altogether when roughly mobile. Doesn’t appear to be responsive, either.

http://trdesign.wpengine.com/maxit/ <http://trdesign.wpengine.com/maxit/>

Check under the Cost-Basis drop down.

Sincerely,

David Zizza, TeKno Ziz
(617) 543-3971 cell    (978) 663-0951 home office
david@teknoziz.com <mailto:david@teknoziz.com>
teknoziz.com <http://teknoziz.com/>

**Comment by themorgantown** [comment]
> But it seems as though the iFrame does not encompass the size of the animation, it’s about a third of the height.

Iframes can't dynamically adjust their height without some outside help, so in your situation the best method is to use the `<div>` method. Iframes are best for embedded documents that have a fixed height and no responsive features. Responsive document really depend on having a good sense of their outside dimensions (something iframes are not great at providing, especially within Wordpress themes).
