### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by themorgantown** [tumult/hype-wordpress-plugin#5]
wordpress 4.8., PHP version 5.6.30-0+deb8u1

`prefix . 'hypeanimations'; ?>get_charset_collate(); $sql = "CREATE TABLE $table_name ( id int(9) NOT NULL AUTO_INCREMENT, nom varchar(150) DEFAULT '' NOT NULL, slug varchar(150) DEFAULT '' NOT NULL, code text NOT NULL, updated INT(11) NOT NULL, container ENUM('none','div','iframe') NOT NULL, containerclass VARCHAR(150) NOT NULL, UNIQUE KEY id (id) ) $charset_collate;";	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' ); dbDelta( $sql ); if ($installed_ver=='') { add_option( 'hypeanimations_db_version', $hypeanimations_db_version ); } else { update_option( "hypeanimations_db_version", $hypeanimations_db_version ); } $update = $wpdb -> query("UPDATE ".$table_name." SET container='none'"); } $upload_dir = wp_upload_dir(); if (!file_exists($upload_dir['basedir'].'/hypeanimations/')) { mkdir($upload_dir['basedir'].'/hypeanimations/'); } if (!file_exists($upload_dir['basedir'].'/hypeanimations/tmp/')) { mkdir($upload_dir['basedir'].'/hypeanimations/tmp/'); } } function hypeanimations_install() { global $wpdb; global $hypeanimations_db_version; global $table_name; $charset_collate = $wpdb->get_charset_collate(); $sql = "CREATE TABLE $table_name ( id int(9) NOT NULL AUTO_INCREMENT, nom varchar(150) DEFAULT '' NOT NULL, slug varchar(150) DEFAULT '' NOT NULL, code text NOT NULL, updated INT(11) NOT NULL, container ENUM('none','div','iframe') NOT NULL, containerclass VARCHAR(150) NOT NULL, UNIQUE KEY id (id) ) $charset_collate;";	require_once( ABSPATH . 'wp-admin/includes/upgrade.php' ); dbDelta( $sql ); add_option( 'hypeanimations_db_version', $hypeanimations_db_version ); } register_activation_hook(FILE,'hypeanimations_install'); ?>
Parse error: syntax error, unexpected '}' in /var/www/mysite.com/htdocs/wp-content/plugins/hype-wordpress-plugin-master/includes/functions.php on line 16`

via: [https://forums.tumult.com/t/hype-animations-wordpress-plugin/11074/4](https://forums.tumult.com/t/hype-animations-wordpress-plugin/11074/4)

related: https://stackoverflow.com/questions/13960514/how-to-adapt-my-plugin-to-multisite/

**Comment by alexlii1971** [comment]
Got it. 
Thanks.

**Comment by themorgantown** [comment]
This update resolves the Multisite issue: https://github.com/tokkonopapa/hype-wordpress-plugin/commit/92d4cb0e52bdc5d2c585c8cd7b486eafa3012264

In process of merging. Thanks @alexlii1971 and @tokkonopapa

**Comment by yumyo** [comment]
Same here but I am not on multisite.

**Comment by themorgantown** [comment]
> Same here but I am not on multisite. Also using the latest version. 

@yumyo Can you share your error log?

**Comment by alexlii1971** [comment]
Hello,

Is it already merge?

Alex

**Comment by themorgantown** [comment]
@alexlii1971 Yes the changes from @tokkonopapa were merged here: 
https://github.com/tumult/hype-wordpress-plugin/commit/1fc895eeef6a066147bdd60e27ff56b25b78aace

**Comment by themorgantown** [comment]
Closing ( https://forums.tumult.com/t/hype-animations-wordpress-plugin-beta/11074/18?u=daniel )
